services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket_db
    environment:
      POSTGRES_DB: ticket_reservation
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: